### ISSUE TITLE
[feat] 폴더 관리 페이지 UI 구현

### ISSUE THREAD

**Issue by yeona813** [KUSITMS-CORECORD/CORECORD_FE#27]
## Description
어떤 작업에 관한 이슈 인가요?

## Todo
- [x] 폴더 관리 페이지 UI
- [x] 폴더 관리 삭제 UI
- [x] 폴더 관리 추가 UI
- [x] 폴더 관리 이름 수정 UI

## ETC
기타 사항
