### ISSUE TITLE
[refactor] : global로 정의된 font 적용하기 

### ISSUE THREAD

**Issue by yeona813** [KUSITMS-CORECORD/CORECORD_FE#35]
## Description
어떤 작업에 관한 이슈 인가요?
 global로 정의된 font 적용하기 

refactor 목적 : global.ts에 정의된 h1~h6 태그 적용 가능한 부분 교체하기 

## Todo
- [x] common component
- [x] 홈 페이지
- [x] 마이 페이지
- [x] 경험 리스트 페이지
- [x] 폴더 관리 페이지
- [x] 키워드 경험 페이지
- [x] 역량 레포트 페이지

## ETC
기타 사항
